# Generated by Django 5.0 on 2024-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=100)),
                ('pass2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
