# Generated by Django 5.0 on 2024-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
