# Generated by Django 5.0 on 2024-03-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contact',
        ),
    ]
