# Generated by Django 5.0 on 2024-03-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_alter_contactus_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
